Changes for AC-187
casework/CASE-Examples pull request #15
Opened 2021-07-31 19:52 UTC by red-ship-it

2021-07-31 19:58 UTC, red-ship-it commented on examples/illustrations/Oresteia/Oresteia.json
> +                    ],
The above is in a json array but I'm not sure if in this case this is OK as I have noted a usage of this that is the similar from the accounts example (https://github.com/casework/CASE-Examples/blob/b0d6daf461b63c6e23d7439ea41050ca60017dd3/examples/illustrations/accounts/accounts.json#L36-L40) 

Also this is what is outlined as the usage in the slides I am working off.

2021-08-11 18:35 UTC, ajnelson-nist commented
@red-ship-it , can you merge in the `master` branch, resolving conflicts, and push the update?  I can review the PR then.

2021-08-11 19:14 UTC, ajnelson-nist requested changes

2021-08-11 19:14 UTC, ajnelson-nist commented on examples/illustrations/Oresteia/Oresteia.json
> +                        "@value": " 2017-06-21T06:36:24.35Z"
A typo has been introduced.  Please remove this whitespace.

2021-08-11 19:19 UTC, red-ship-it commented on examples/illustrations/file/file.json
> +            "@id": "kb:android_device1-uuid",
Bookmarking thanks

2021-08-11 19:20 UTC, ajnelson-nist commented on examples/illustrations/Oresteia/Oresteia.json
> +                        "@value": " 2017-06-21T06:36:24.35Z"
Resolved in e7e74e9.  Thanks!

2021-08-11 19:20 UTC, ajnelson-nist approved these changes

2021-08-11 19:20 UTC, merged